export const SET_CONVERSATIONS = "SET_CONVERSATIONS";
export const SET_CONVERSATION_MESSAGES = "SET_CONVERSATION_MESSAGES";
export const SET_SELECTED_CONVERSATION = "SET_SELECTED_CONVERSATION";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_CONVERSATION_NEW_MESSAGE = "SET_CONVERSATION_NEW_MESSAGE";
export const CONV_LOADING = "CONV_LOADING";
export const SET_SENDING_MESSAGE = "SET_SENDING_MESSAGE";
